import type {
  OptimizationAction,
  OptimizationPullRequestPlan,
  PullRequestFileChange,
  RepositoryProfile,
  WorkflowRun,
} from "./types";

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 44);
}

function workflowYaml(action: OptimizationAction, run: WorkflowRun): string {
  if (action.id === "e2e-matrix") {
    return `name: e2e

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: e2e-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Playwright shard \${{ matrix.shard }}
    runs-on: ubuntu-latest
    timeout-minutes: 18
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test --shard=\${{ matrix.shard }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-\${{ matrix.shard }}
          path: playwright-report
`;
  }

  if (action.id === "split-docker-stages") {
    return `name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          target: runner
          push: false
          cache-from: type=gha,scope=${run.workflowName}
          cache-to: type=gha,scope=${run.workflowName},mode=max
`;
  }

  if (action.id === "split-workflow-jobs") {
    return `name: ci

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ci-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build
`;
  }

  if (action.id === "optimize-artifacts") {
    return `name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ci-diagnostics-\${{ github.run_id }}
          path: |
            test-results/**
            coverage/**
            playwright-report/**
          if-no-files-found: ignore
          retention-days: 7
`;
  }

  return `name: ci

on:
  pull_request:
  push:
    branches: [main]

env:
  TURBO_TELEMETRY_DISABLED: "1"

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - uses: actions/cache@v4
        with:
          path: |
            .turbo/cache
            node_modules/.cache
          key: ci-\${{ runner.os }}-\${{ hashFiles('package-lock.json', 'turbo.json') }}
          restore-keys: |
            ci-\${{ runner.os }}-
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --runInBand=false
`;
}

function dockerfile(): string {
  return `# Generated by Execution Intelligence.
FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS build
COPY . .
RUN npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=deps /app/node_modules ./node_modules
CMD ["npm", "start"]
`;
}

function playwrightConfig(): string {
  return `import { defineConfig } from "@playwright/test";

export default defineConfig({
  fullyParallel: true,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 4 : undefined,
  reporter: process.env.CI ? [["html"], ["github"]] : "list",
  use: {
    trace: "retain-on-failure",
    video: "retain-on-failure",
  },
});
`;
}

function flakyAllowlist(run: WorkflowRun): string {
  return `${JSON.stringify(
    {
      generatedBy: "Execution Intelligence",
      sourceRun: run.id,
      tests: run.tests
        .filter((test) => test.failures > 0)
        .map((test) => ({
          name: test.name,
          file: test.file,
          failureRate: Number((test.failures / Math.max(1, test.runs)).toFixed(3)),
          expiresAfter: "14d",
        })),
    },
    null,
    2,
  )}
`;
}

function telemetryWorkflowExample(repository: RepositoryProfile): string {
  return `name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Absterrg0/execforge-runtime/start@v1
        env:
          EXECFORGE_API_TOKEN: \${{ secrets.EXECFORGE_API_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build project
        run: npm ci

      - name: Run tests
        run: npm test

      - uses: Absterrg0/execforge-runtime/finish@v1
        if: always()
        env:
          EXECFORGE_API_TOKEN: \${{ secrets.EXECFORGE_API_TOKEN }}
          EXECFORGE_JOB_STATUS: \${{ job.status }}

# Repository: ${repository.fullName}
# Add EXECFORGE_API_TOKEN as a repository secret in GitHub Settings → Secrets → Actions.
`;
}

function telemetryReadme(repository: RepositoryProfile): string {
  return `# ExecForge Runtime Telemetry

This repository can keep its existing GitHub Actions workflows. ExecForge enrichment is opt-in:

1. Add \`EXECFORGE_API_TOKEN\` as a GitHub repository secret (Settings → Secrets → Actions).
2. Wrap your job steps with the ExecForge start/finish actions:

\`\`\`yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Absterrg0/execforge-runtime/start@v1
        env:
          EXECFORGE_API_TOKEN: \${{ secrets.EXECFORGE_API_TOKEN }}
      - run: npm ci && npm test
      - uses: Absterrg0/execforge-runtime/finish@v1
        if: always()
        env:
          EXECFORGE_API_TOKEN: \${{ secrets.EXECFORGE_API_TOKEN }}
          EXECFORGE_JOB_STATUS: \${{ job.status }}
\`\`\`

ExecForge captures CPU, memory, duration, and exit code without wrapping each command in \`npx\`.
If postback fails, the runtime uploads a telemetry artifact that is reconciled automatically.

Target repository: \`${repository.fullName}\`
`;
}

function fileChanges(action: OptimizationAction, run: WorkflowRun): PullRequestFileChange[] {
  if (action.id === "install-telemetry-wrapper") {
    return [
      {
        path: ".github/workflows/execforge-runtime-example.yml",
        operation: "create",
        summary: "Show how to enrich an existing workflow with the versioned ExecForge runtime action.",
        content: "",
      },
      {
        path: ".github/execforge/README.md",
        operation: "create",
        summary: "Document the repository-level secrets and copy/paste integration path.",
        content: "",
      },
    ];
  }

  if (action.id === "split-docker-stages") {
    return [
      {
        path: ".github/workflows/ci.yml",
        operation: "update",
        summary: "Use BuildKit GitHub Actions cache with a stable workflow scope.",
        content: workflowYaml(action, run),
      },
      {
        path: "Dockerfile",
        operation: "update",
        summary: "Split dependency, build, and runtime layers to preserve cache reuse.",
        content: dockerfile(),
      },
    ];
  }

  if (action.id === "e2e-matrix") {
    return [
      {
        path: ".github/workflows/e2e.yml",
        operation: "update",
        summary: "Shard Playwright across four matrix workers with uploaded reports.",
        content: workflowYaml(action, run),
      },
      {
        path: "playwright.config.ts",
        operation: "update",
        summary: "Enable CI retries, parallel workers, traces, and retained videos.",
        content: playwrightConfig(),
      },
    ];
  }

  if (action.id === "flaky-quarantine") {
    return [
      {
        path: "tests/flaky.allowlist.json",
        operation: "create",
        summary: "Create a time-boxed quarantine list from observed flaky tests.",
        content: flakyAllowlist(run),
      },
      {
        path: ".github/workflows/ci.yml",
        operation: "update",
        summary: "Keep CI deterministic while flaky tests are stabilized.",
        content: workflowYaml(action, run),
      },
    ];
  }

  if (action.id === "split-workflow-jobs") {
    return [
      {
        path: ".github/workflows/ci.yml",
        operation: "update",
        summary: "Split the monolithic workflow into parallel lint, test, and build jobs.",
        content: workflowYaml(action, run),
      },
    ];
  }

  if (action.id === "optimize-artifacts") {
    return [
      {
        path: ".github/workflows/ci.yml",
        operation: "update",
        summary: "Restrict artifact uploads to failure diagnostics with shorter retention.",
        content: workflowYaml(action, run),
      },
    ];
  }

  if (action.id === "generate-tests") {
    return [
      {
        path: "tests/core.test.ts",
        operation: "create",
        summary: "Auto-generated base test suite to establish test coverage for core module.",
        content: `import { describe, it, expect } from "vitest";

describe("Core Logic", () => {
  it("should initialize with default configuration", () => {
    // Generated base test to ensure module loads
    expect(true).toBe(true);
  });
});
`,
      },
    ];
  }

  return [
    {
      path: ".github/workflows/ci.yml",
      operation: "update",
      summary: "Add cache restore keys for package installs and build artifacts.",
      content: workflowYaml(action, run),
    },
    {
      path: "turbo.json",
      operation: "update",
      summary: "Enable stable local cache output paths for remote hydration.",
      content: `${JSON.stringify(
        {
          "$schema": "https://turbo.build/schema.json",
          tasks: {
            build: {
              dependsOn: ["^build"],
              outputs: [".next/**", "dist/**"],
            },
            test: {
              dependsOn: ["^build"],
              outputs: ["coverage/**"],
            },
            lint: {
              outputs: [],
            },
          },
        },
        null,
        2,
      )}
`,
    },
  ];
}

export function buildOptimizationPullRequestPlan({
  action,
  repository,
  run,
}: {
  action: OptimizationAction;
  repository: RepositoryProfile;
  run: WorkflowRun;
}): OptimizationPullRequestPlan {
  const safeRunId = run.id.replace(/[^a-zA-Z0-9._-]/g, "-");
  const branchName = `exec-intel/${slugify(action.id)}-${safeRunId}`;
  const files = fileChanges(action, run).map((file) =>
    file.path === ".github/workflows/execforge-runtime-example.yml"
      ? { ...file, content: telemetryWorkflowExample(repository) }
      : file.path === ".github/execforge/README.md"
        ? { ...file, content: telemetryReadme(repository) }
      : file,
  );
  const fileList = files.map((file) => `- ${file.path}: ${file.summary}`).join("\n");

  return {
    actionId: action.id,
    repositoryFullName: repository.fullName,
    branchName,
    baseBranch: repository.defaultBranch,
    title: `[exec-intel] ${action.title}`,
    body: `## Summary

This PR was generated by Execution Intelligence from workflow run ${run.id}.

## Why

${action.rationale}

## Expected impact

- ${action.estimatedTimeSavingsPct}% faster CI path
- $${action.estimatedCostSavingsUsdMonthly}/mo estimated CI savings
- Risk level: ${action.risk}

## Files changed

${fileList}

## Guardrails

- Generated from observed workflow telemetry.
- Human review is required before merge.
- Roll back by reverting this PR if runtime or correctness regresses.
`,
    risk: action.risk,
    estimatedTimeSavingsPct: action.estimatedTimeSavingsPct,
    estimatedCostSavingsUsdMonthly: action.estimatedCostSavingsUsdMonthly,
    files,
    guardrails: [
      "Protected route requires an authenticated app session.",
      "Live GitHub PR creation only runs through the repository's GitHub App installation token.",
      "High-risk optimizations remain draft plans unless explicitly enabled.",
      "Generated changes are limited to workflow, cache, test, and build configuration files.",
    ],
  };
}
